### ISSUE TITLE
how to get registration link

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [SoftwareCountry/Perseus#472]
I installed and make it to work

However, i dont get the registration link. 

How can i set this up or install to ignore log in 

thanks

**Comment by bradanton** [comment]
Hi,

Do you mean email with activation link for new user?

Thanks,
Anton

**Comment by javier-gracia-tabuenca-tuni** [comment]
yes i dont get the email with the activation link, 
probably some setings on my virtual machine allow to send eamails

Is there an option to skip this for testing pourposes, or other solution I missed 
thanks

**Comment by bradanton** [comment]
you can try to use test user.
user name: test_email@test.ru
pswd: test

Also we will add option to skip registration in next release. 
For multi user access you need to setup SMTP server, we will update readme soon.

**Comment by bradanton** [comment]
setup SMTP server:
https://github.com/SoftwareCountry/Perseus#configuring-smtp-server-settings
