### ISSUE TITLE
provided user and password not working 

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [SoftwareCountry/Perseus#590]
I have started each container separately. 
I used the default empty back-envs.txt file. 
However, the provided "single-user" user and password doesnt work

**Comment by chMatvey** [comment]
Hello,
What username and password do you use?
And could you send error message and error code?

**Comment by javier-gracia-tabuenca-tuni** [comment]
thanks for fast response
I installed each container as descrived in the main page. Leaving all options ad default. 
Im able to brose to the main page. 
I try with 
email: perseus@softwarecountry.com
password: perseus 
It just tells me that the user dont exists. There is no error

**Comment by chMatvey** [comment]
Probably the problem is long database deploy. Could you check database container log by this command?

`docker logs perseus-database`

**Comment by javier-gracia-tabuenca-tuni** [comment]
seems you are correct. 
init.db stops at the begining 
not sure why cant find the vocabuary tables, bcs they are correctly unziped on that folder

**Comment by chMatvey** [comment]
Have you changed the vocabulary link in this dockerfile: https://github.com/SoftwareCountry/Perseus/blob/master/database/Dockerfile ?
like described in this section [vocabulary](https://github.com/SoftwareCountry/Perseus#vocabulary)

I tried to start vocabulary container with empty link and default archive. It work in my local env.

**Comment by javier-gracia-tabuenca-tuni** [comment]
Sorry, i cleaned the ivm and run it again. 
Works as inteded.
