### ISSUE TITLE
Server Error when Scanning CSV Files

### ISSUE THREAD

**Issue by Zwky26** [SoftwareCountry/Perseus#626]
When importing data as a CSV file, Perseus throws a server error: 
`Server error occurred. Please contact our support... 
Cannot link tables. Unable to create source schema by source current transaction is aborted, commands ignored until end of transaction block`
This occurs inconsistently, independent of what source file is being uploaded. After 1-7 attempts of reuploading the same file (clicking cancel, ok, link tables) the request goes through. The same error message also occasionally occurs when using the 'Open Mapping' feature and the 'Create View' function. 

![compressed2](https://user-images.githubusercontent.com/59004211/175326841-24626045-c182-491b-8f4c-98f65328c077.gif)

Tested on Chrome 102.0.5005.115 and Firefox 101.0.1. Network connection is stable. Occurs regardless of number of files uploaded (tried 1, 2, and 3 csv files in batch upload). Renaming files does not seem to affect consistency of upload.

**Comment by bradanton** [comment]
Hi Zack, 

We had issue with opened connections, fix was added and perseus was re-deployed. Please let us know if issue still exists.

Thanks,
Anton

**Comment by Zwky26** [comment]
It is working consistently now! I will comment if it ever breaks during testing, but it's looking good
