### ISSUE TITLE
SQL Engine does not recognize columns, tables based on case

### ISSUE THREAD

**Issue by Zwky26** [SoftwareCountry/Perseus#627]
"Create View" function and transformation SQL function in link table do not work when any part of the column name is capitalized. This could be problematic as SynPUF data is defaulted to having all columns titled in uppercase, so generating a default configuration may need to somehow sanitize the original format. It is also inconsistent with UI of Source Columns, see image 1. 

Demonstration: column DESYNPUF_ID is not being identified, even though it is present. Backend is likely only querying "select t1.desynpuf_id". One solution may be to have schema_parser automatically "lower()" all column titles to sanitize input. Another is to adjust the UI to indicate the case of columns. Alternatively, including another tooltip on upper-case lower-case practice, see Image 2.

https://user-images.githubusercontent.com/59004211/175362694-53cdf152-1b10-4e1f-ac3d-c3f23caa4e39.mp4

Image1:
![image1](https://user-images.githubusercontent.com/59004211/175353926-b759460e-8580-4a95-b85a-55b2715c55a4.PNG)

Image2: 
![image2](https://user-images.githubusercontent.com/59004211/175366515-50c9ba9a-b043-4767-89ff-088954f674e8.PNG)

**Comment by chMatvey** [comment]
@Zwky26 fixed, please check
