### ISSUE TITLE
SQL ISNULL function not implemented

### ISSUE THREAD

**Issue by Zwky26** [SoftwareCountry/Perseus#628]
Function "ISNULL" is either not recognized or defined. Functionality should be similar to base SQL function, able to handle input 
"(varchar, varchar)" or "(int, int)" 
![image](https://user-images.githubusercontent.com/59004211/176947713-0cfd75d0-95de-4bbd-a68f-1cd35396b8b1.png)
![image](https://user-images.githubusercontent.com/59004211/176947920-e9826e36-be93-466d-8842-84089b662ad8.png)

Adding explicit type castings does not affect result e.g
`ISNULL(race_concept_id, 0) //does not work`
`ISNULL(cast(race_concept_id as text), cast(0 as text)) //does not work`
`ISNULL(cast(race_concept_id as text), 0) //does not work`
`ISNULL(race_concept_id, cast(0 as text)) //does not work`

**Comment by bradanton** [comment]
Hi @Zwky26,

Perseus uses postgres syntax, try this - **coalesce(field, 'Empty')**

Thanks,
Anton

**Comment by Zwky26** [comment]
That works! A tangential fix to this is to remove the ISNULL quick function from within the SQL function popup, as seen below.

![image](https://user-images.githubusercontent.com/59004211/176964368-b27bf728-ad03-4047-bd0f-78210dca5785.png)
