### ISSUE TITLE
Preserving SQL Whitespace in "Create View"

### ISSUE THREAD

**Issue by Zwky26** [SoftwareCountry/Perseus#629]
When making new views, the SQL logic may get extensively long. For improved visibility, is it possible to adjust/preserve the whitespace between writing? 

https://user-images.githubusercontent.com/59004211/176968162-26ad4a4e-df7c-4ced-ab02-1b5658eec69a.mp4

**Comment by bradanton** [comment]
Thanks @Zwky26, currently we working on updating "Create View" element. 
We going to add formatter for SQL statements, as well as fix for [https://github.com/SoftwareCountry/Perseus/issues/627](url)

**Comment by chMatvey** [comment]
@Zwky26 done

**Comment by Zwky26** [comment]
Tested and confirmed working
