### ISSUE TITLE
FEATURE (Medium Prio): Connect USAGI table to main Perseus features

### ISSUE THREAD

**Issue by Zwky26** [SoftwareCountry/Perseus#655]
After using the "Code Mapping" feature, allowing the user to export the mapping as a csv, or directly into the main page as another table would greatly speed up workflow

**Comment by bradanton** [comment]
@Zwky26 currently the mapping stored to Perseus embedded vocabulary database (source_to_concept_map table).
You can use new mapping for _concept_id fields through concept configuration dialog, example below:
![image](https://user-images.githubusercontent.com/13117785/181748319-706f758c-2bab-4bfc-88a8-9ebb5eac6b58.png)

![image](https://user-images.githubusercontent.com/13117785/181748644-a9c54c05-dbf5-45cf-a515-ca5f5dbd880f.png)

![image](https://user-images.githubusercontent.com/13117785/181749190-d5ff56ab-79dd-45e5-9c6a-b8a804c845ae.png)

**Comment by Zwky26** [comment]
Amazing. Thanks for letting me know!
