### ISSUE TITLE
Error building frontend

### ISSUE THREAD

**Issue by gmestdac** [SoftwareCountry/Perseus#702]
When building the frontend  an error occurs at the npm run step:

  [build-step 7/7] RUN npm run build:prod:
#15 0.741 > ui@0.0.0 build:prod /usr/src/app
#15 0.741 > ng build --configuration production
#15 0.741
#15 2.007 An unhandled exception occurred: Cannot find module 'node:assert'
#15 2.007 Require stack:
#15 2.007 - /usr/src/app/node_modules/@ngtools/webpack/src/resource_loader.js
#15 2.007 - /usr/src/app/node_modules/@ngtools/webpack/src/ivy/plugin.js
#15 2.007 - /usr/src/app/node_modules/@ngtools/webpack/src/ivy/index.js
#15 2.007 - /usr/src/app/node_modules/@ngtools/webpack/src/index.js
#15 2.007 - /usr/src/app/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
#15 2.007 - /usr/src/app/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
#15 2.007 - /usr/src/app/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/models/architect-command.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/commands/build-impl.js
#15 2.007 - /usr/src/app/node_modules/@angular-devkit/schematics/tools/export-ref.js
#15 2.007 - /usr/src/app/node_modules/@angular-devkit/schematics/tools/index.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/utilities/json-schema.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/models/command-runner.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/lib/cli/index.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/lib/init.js
#15 2.007 - /usr/src/app/node_modules/@angular/cli/bin/ng
#15 2.007 See "/tmp/ng-9Ixw6a/angular-errors.log" for further details.
#15 2.023 npm ERR! code ELIFECYCLE
#15 2.023 npm ERR! syscall spawn
#15 2.023 npm ERR! file sh
#15 2.023 npm ERR! errno ENOENT
#15 2.026 npm ERR! ui@0.0.0 build:prod: `ng build --configuration production`
#15 2.026 npm ERR! spawn ENOENT
#15 2.026 npm ERR!
#15 2.026 npm ERR! Failed at the ui@0.0.0 build:prod script.
#15 2.026 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#15 2.037
#15 2.037 npm ERR! A complete log of this run can be found in:
#15 2.037 npm ERR!     /root/.npm/_logs/2022-12-16T13_37_20_918Z-debug.log

I did have to add "RUN npm config set strict-ssl false" to the dockerFile due to ssl certificate issues, but I believe this is unrelated.
A quick stackoverflow search tells me this might be fixed by switching to a later version of node.js, but simply adjusting this in the dockerFile causes compatibility issues with the angular version

**Comment by EugZ** [comment]
According to https://github.com/SoftwareCountry/Perseus/commit/3e2dc78983dbff61b86b17bbbfe04ad2142d0892 this issue occured due to redundant upgrade of dependecy. In `package.json` we need to rollback dev dependency `"@angular-devkit/build-angular"` to `"~12.2.18"` version as it was before.

**Comment by gmestdac** [comment]
I manually made this change and it did indeed fix the issue

**Comment by ssamus** [comment]
done
