### ISSUE TITLE
Question of feasibility of paired foreign keys? 

### ISSUE THREAD

**Issue by rtmill** [SoftwareCountry/Perseus#721]
I'm curious about how the Perseus team views the level of difficulty around enabling functionality to include relationships between clinical tables in OMOP to which there isn't a standard foreign key. e.g., when a measurement relates to a condition but there isn't a condition_occurrence_id FK within the measurement table. 

The two approaches in OMOP:
- the fact relationship table (or a revised version of it)
- the 'two-part foreign key' mechanism that keeps appearing in OMOP. The first part referencing the ([concept](https://athena.ohdsi.org/search-terms/terms?vocabulary=CDM&conceptClass=Field&page=1&pageSize=15&query=)) field of a table, the second part referencing the ID of that field. This exists in [MEASUREMENT](https://ohdsi.github.io/CommonDataModel/cdm54.html#MEASUREMENT), [EPISODE_EVENT](https://ohdsi.github.io/CommonDataModel/cdm54.html#EPISODE_EVENT) and sounds like it will be added to NOTE_NLP soon, as was recently ratified, to connect the NLP derivations to records in the clinical tables. 

From my perspective it's a bit of a difficult mechanism to universally code into this type of machinery, where your source data links together in a dynamic way - say for instance a single condition has 15 measurements that relate to it as "modifiers", and both are identity tables.... 

Another question would be, in terms of implementation within Perseus, I'm curious if there are thoughts as to which would be easier, the fact_relationship approach or the 'two-part foreign key'/'polymorphic key' mechanism?  

For context, I'm looking to plan ahead with decisions around the Oncology WG for integration down the road. 

Thanks,

**Comment by bradanton** [comment]
Hi Robert,

In the Perseus project we uses exiting CDM schemas. It is better to address this question to the OHDSI forum.

Thanks,
Anton
